

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MonthPage.xaml.h"




void ::ComCal_v1::MonthPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///MonthPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///MonthPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the TextBlock named 'MonthPageTitle'
    MonthPageTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"MonthPageTitle"));
    // Get the Grid named 'MonthGrid'
    MonthGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"MonthGrid"));
    // Get the TextBlock named 'helperBlock'
    helperBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"helperBlock"));
    // Get the TextBox named 'userInputBox'
    userInputBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"userInputBox"));
    // Get the TextBlock named 'feedbackBlock'
    feedbackBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"feedbackBlock"));
    // Get the TextBlock named 'commandHelpSheet'
    commandHelpSheet = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"commandHelpSheet"));
    // Get the TextBlock named 'monthPage_Day1'
    monthPage_Day1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthPage_Day1"));
    // Get the TextBlock named 'monthPage_Day2'
    monthPage_Day2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthPage_Day2"));
    // Get the TextBlock named 'monthPage_Day3'
    monthPage_Day3 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthPage_Day3"));
    // Get the TextBlock named 'monthPage_Day4'
    monthPage_Day4 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthPage_Day4"));
    // Get the TextBlock named 'monthPage_Day5'
    monthPage_Day5 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthPage_Day5"));
    // Get the TextBlock named 'monthPage_Day6'
    monthPage_Day6 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthPage_Day6"));
    // Get the TextBlock named 'monthPage_Day7'
    monthPage_Day7 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthPage_Day7"));
    // Get the TextBlock named 'monthDate_grid11'
    monthDate_grid11 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid11"));
    // Get the TextBlock named 'monthDate_grid12'
    monthDate_grid12 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid12"));
    // Get the TextBlock named 'monthDate_grid13'
    monthDate_grid13 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid13"));
    // Get the TextBlock named 'monthDate_grid14'
    monthDate_grid14 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid14"));
    // Get the TextBlock named 'monthDate_grid15'
    monthDate_grid15 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid15"));
    // Get the TextBlock named 'monthDate_grid16'
    monthDate_grid16 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid16"));
    // Get the TextBlock named 'monthDate_grid17'
    monthDate_grid17 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid17"));
    // Get the TextBlock named 'monthDate_grid21'
    monthDate_grid21 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid21"));
    // Get the TextBlock named 'monthDate_grid22'
    monthDate_grid22 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid22"));
    // Get the TextBlock named 'monthDate_grid23'
    monthDate_grid23 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid23"));
    // Get the TextBlock named 'monthDate_grid24'
    monthDate_grid24 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid24"));
    // Get the TextBlock named 'monthDate_grid25'
    monthDate_grid25 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid25"));
    // Get the TextBlock named 'monthDate_grid26'
    monthDate_grid26 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid26"));
    // Get the TextBlock named 'monthDate_grid27'
    monthDate_grid27 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid27"));
    // Get the TextBlock named 'monthDate_grid31'
    monthDate_grid31 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid31"));
    // Get the TextBlock named 'monthDate_grid32'
    monthDate_grid32 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid32"));
    // Get the TextBlock named 'monthDate_grid33'
    monthDate_grid33 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid33"));
    // Get the TextBlock named 'monthDate_grid34'
    monthDate_grid34 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid34"));
    // Get the TextBlock named 'monthDate_grid35'
    monthDate_grid35 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid35"));
    // Get the TextBlock named 'monthDate_grid36'
    monthDate_grid36 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid36"));
    // Get the TextBlock named 'monthDate_grid37'
    monthDate_grid37 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid37"));
    // Get the TextBlock named 'monthDate_grid41'
    monthDate_grid41 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid41"));
    // Get the TextBlock named 'monthDate_grid42'
    monthDate_grid42 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid42"));
    // Get the TextBlock named 'monthDate_grid43'
    monthDate_grid43 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid43"));
    // Get the TextBlock named 'monthDate_grid44'
    monthDate_grid44 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid44"));
    // Get the TextBlock named 'monthDate_grid45'
    monthDate_grid45 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid45"));
    // Get the TextBlock named 'monthDate_grid46'
    monthDate_grid46 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid46"));
    // Get the TextBlock named 'monthDate_grid47'
    monthDate_grid47 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid47"));
    // Get the TextBlock named 'monthDate_grid51'
    monthDate_grid51 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid51"));
    // Get the TextBlock named 'monthDate_grid52'
    monthDate_grid52 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid52"));
    // Get the TextBlock named 'monthDate_grid53'
    monthDate_grid53 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid53"));
    // Get the TextBlock named 'monthDate_grid54'
    monthDate_grid54 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid54"));
    // Get the TextBlock named 'monthDate_grid55'
    monthDate_grid55 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid55"));
    // Get the TextBlock named 'monthDate_grid56'
    monthDate_grid56 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid56"));
    // Get the TextBlock named 'monthDate_grid57'
    monthDate_grid57 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"monthDate_grid57"));
    // Get the TextBlock named 'date_tasks11'
    date_tasks11 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks11"));
    // Get the TextBlock named 'date_tasks12'
    date_tasks12 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks12"));
    // Get the TextBlock named 'date_tasks13'
    date_tasks13 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks13"));
    // Get the TextBlock named 'date_tasks14'
    date_tasks14 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks14"));
    // Get the TextBlock named 'date_tasks15'
    date_tasks15 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks15"));
    // Get the TextBlock named 'date_tasks16'
    date_tasks16 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks16"));
    // Get the TextBlock named 'date_tasks17'
    date_tasks17 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks17"));
    // Get the TextBlock named 'date_tasks21'
    date_tasks21 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks21"));
    // Get the TextBlock named 'date_tasks22'
    date_tasks22 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks22"));
    // Get the TextBlock named 'date_tasks23'
    date_tasks23 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks23"));
    // Get the TextBlock named 'date_tasks24'
    date_tasks24 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks24"));
    // Get the TextBlock named 'date_tasks25'
    date_tasks25 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks25"));
    // Get the TextBlock named 'date_tasks26'
    date_tasks26 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks26"));
    // Get the TextBlock named 'date_tasks27'
    date_tasks27 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks27"));
    // Get the TextBlock named 'date_tasks31'
    date_tasks31 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks31"));
    // Get the TextBlock named 'date_tasks32'
    date_tasks32 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks32"));
    // Get the TextBlock named 'date_tasks33'
    date_tasks33 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks33"));
    // Get the TextBlock named 'date_tasks34'
    date_tasks34 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks34"));
    // Get the TextBlock named 'date_tasks35'
    date_tasks35 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks35"));
    // Get the TextBlock named 'date_tasks36'
    date_tasks36 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks36"));
    // Get the TextBlock named 'date_tasks37'
    date_tasks37 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks37"));
    // Get the TextBlock named 'date_tasks41'
    date_tasks41 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks41"));
    // Get the TextBlock named 'date_tasks42'
    date_tasks42 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks42"));
    // Get the TextBlock named 'date_tasks43'
    date_tasks43 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks43"));
    // Get the TextBlock named 'date_tasks44'
    date_tasks44 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks44"));
    // Get the TextBlock named 'date_tasks45'
    date_tasks45 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks45"));
    // Get the TextBlock named 'date_tasks46'
    date_tasks46 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks46"));
    // Get the TextBlock named 'date_tasks47'
    date_tasks47 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks47"));
    // Get the TextBlock named 'date_tasks51'
    date_tasks51 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks51"));
    // Get the TextBlock named 'date_tasks52'
    date_tasks52 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks52"));
    // Get the TextBlock named 'date_tasks53'
    date_tasks53 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks53"));
    // Get the TextBlock named 'date_tasks54'
    date_tasks54 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks54"));
    // Get the TextBlock named 'date_tasks55'
    date_tasks55 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks55"));
    // Get the TextBlock named 'date_tasks56'
    date_tasks56 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks56"));
    // Get the TextBlock named 'date_tasks57'
    date_tasks57 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"date_tasks57"));
}

void ::ComCal_v1::MonthPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::ComCal_v1::MonthPage::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&MonthPage::userEnterCom);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ComCal_v1::MonthPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MonthPage::defaultView);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

